[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['cd inter-media-app && npm ci']

[phases.build]
cmds = ['cd inter-media-app && npm run build']

[start]
cmd = 'cd inter-media-app && npm start'
